# Generated by Django 2.2.5 on 2020-08-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='superhost',
            new_name='host',
        ),
    ]
