# Generated by Django 2.2.5 on 2020-08-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'en'), ('kr', 'kr')], default='kr', max_length=2),
        ),
    ]
