# Generated by Django 2.2.5 on 2020-08-11 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200811_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='business_close',
        ),
        migrations.RemoveField(
            model_name='store',
            name='business_open',
        ),
        migrations.RemoveField(
            model_name='store',
            name='luggage',
        ),
        migrations.RemoveField(
            model_name='store',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='store',
            name='closing_fri',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='closing_mon',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='closing_sat',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='closing_sun',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='closing_thu',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='closing_tue',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='closing_wen',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='luggage_large_store',
            field=models.IntegerField(default=0, help_text='size: confirmed later'),
        ),
        migrations.AddField(
            model_name='store',
            name='luggage_medium_store',
            field=models.IntegerField(default=0, help_text='size: confirmed later'),
        ),
        migrations.AddField(
            model_name='store',
            name='luggage_small_store',
            field=models.IntegerField(default=0, help_text='size: confirmed later'),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_fri',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_mon',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_sat',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_sun',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_thu',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_tue',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_wen',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
