# Generated by Django 2.2.5 on 2020-08-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20200815_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='country',
        ),
        migrations.AddField(
            model_name='store',
            name='store_latitude',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_longitude',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(default='Busan', max_length=80),
        ),
    ]
