# Generated by Django 2.2.5 on 2020-08-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20200820_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_latitude',
            new_name='latitude_store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_longitude',
            new_name='longitude_store',
        ),
    ]
