# Generated by Django 2.2.5 on 2020-08-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20200820_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='price',
        ),
    ]
