# Generated by Django 2.2.5 on 2020-08-27 13:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_remove_store_instant_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='country',
            field=django_countries.fields.CountryField(default='KR', max_length=2),
        ),
    ]
