# Generated by Django 2.2.5 on 2020-08-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_store_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.ForeignKey(blank=True, default='gym', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='stores.StoreType'),
        ),
    ]
